# Generated by Django 4.1.5 on 2023-01-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AWSECSCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "ECS Cluster",
                "verbose_name_plural": "ECS Clusters",
            },
        ),
        migrations.CreateModel(
            name="AWSLoadBalancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("arn", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Load balancer",
                "verbose_name_plural": "Load balancers",
            },
        ),
        migrations.CreateModel(
            name="AWSECSService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("desired_count", models.IntegerField(default=0)),
                ("cluster_name", models.CharField(max_length=30)),
                (
                    "load_balancers",
                    models.ManyToManyField(blank=True, to="aws.awsloadbalancer"),
                ),
            ],
            options={
                "verbose_name": "ECS Service",
                "verbose_name_plural": "ECS Services",
            },
        ),
    ]
