# Generated by Django 4.1.5 on 2023-01-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aws", "0002_awsecscluster"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awsecscluster",
            options={
                "verbose_name": "ECS Cluster",
                "verbose_name_plural": "ECS Clusters",
            },
        ),
        migrations.AlterModelOptions(
            name="awsloadbalancer",
            options={
                "verbose_name": "Load balancer",
                "verbose_name_plural": "Load balancers",
            },
        ),
    ]
